export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

export const FETCH_POST_COMMENTS_REQUEST = 'FETCH_POST_COMMENTS_REQUEST';
export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS';
export const FETCH_POST_COMMENTS_FAIL = 'FETCH_POST_COMMENTS_FAIL';

export const TOGGLE_LIKE_COMMENT_REQUEST = 'TOGGLE_LIKE_COMMENT_REQUEST';
export const TOGGLE_LIKE_COMMENT_SUCCESS = 'TOGGLE_LIKE_COMMENT_SUCCESS';
