export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const FETCH_TIMELINE_POST_REQUEST = 'FETCH_TIMELINE_POST_REQUEST';
export const FETCH_TIMELINE_POST_SUCCESS = 'FETCH_TIMELINE_POST_SUCCESS';
export const FETCH_TIMELINE_POST_FAIL = 'FETCH_TIMELINE_POST_FAIL';

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL';
