export const SOCKET_CONNECT_REQUEST = 'SOCKET_CONNECT_REQUEST';
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS';
export const SOCKET_DISCONNECT_SUCCESS = 'SOCKET_DISCONNECT_SUCCESS';
export const SOCKET_LIVE_USER_FETCHED = 'SOCKET_LIVE_USER_FETCHED';
export const SOCKET_FOLLOW_REQUESTS_UPDATE = 'SOCKET_FOLLOW_REQUESTS_UPDATE';
