export const SOCKET_CONNECT_REQUEST = 'SOCKET_CONNECT_REQUEST';
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS';
export const SOCKET_DISCONNECT_SUCCESS = 'SOCKET_DISCONNECT_SUCCESS';
export const SOCKET_LIVE_USER_FETCHED = 'SOCKET_LIVE_USER_FETCHED';
export const SOCKET_FOLLOW_REQUESTS_UPDATE = 'SOCKET_FOLLOW_REQUESTS_UPDATE';
export const SOCKET_FOLLOW_NOTIFICATION_UPDATE =
  'SOCKET_FOLLOW_NOTIFICATION_UPDATE';
export const SOCKET_USER_DICONNECT_UPDATE = 'SOCKET_USER_DICONNECT_UPDATE';
export const SOCKET_USER_JOIN_UPDATE = 'SOCKET_USER_JOIN_UPDATE';
export const SOCKET_POST_LIKE_REQUEST_UPDATE =
  'SOCKET_POST_LIKE__REQUEST_UPDATE';
export const SOCKET_POST_LIKE_NOTIFICATION_UPDATE =
  'SOCKET_POST_LIKE_NOTIFICATION_UPDATE';
