export const LOGGEDIN_USERDATA_REQUEST = 'LOGGEDIN_USERDATA_REQUEST';
export const LOGGEDIN_USERDATA_SUCCESS = 'LOGGEDIN_USERDATA_SUCCESS';
export const LOGGEDIN_USERDATA_FAIL = 'LOGGEDIN_USERDATA_FAIL';

export const ALL_USERSDATA_REQUEST = 'ALL_USERSDATA_REQUEST';
export const ALL_USERSDATA_SUCCESS = 'ALL_USERSDATA_SUCCESS';
export const ALL_USERSDATA_FAIL = 'ALL_USERSDATA_FAIL';

export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL';
